### ISSUE TITLE
Incomplete checks for permission-related API setRequireOriginal

### ISSUE THREAD

**Issue by wowhhh** [FunkyMuse/KAHelpers#124]
Hi, there, I found a framework API call needs permission, but is not annotated.
The API is `MediaStore.setRequireOriginal(Uri)`, it is added in Android Q, and needs permission `ACCESS_MEDIA_LOCATION`.

It is used in the library in three places 

https://github.com/FunkyMuse/KAHelpers/blob/master/saf/src/main/java/com/crazylegend/saf/SafExtensions.kt#L30
https://github.com/FunkyMuse/KAHelpers/blob/master/saf/src/main/java/com/crazylegend/saf/SafExtensions.kt#L44
https://github.com/FunkyMuse/KAHelpers/blob/master/saf/src/main/java/com/crazylegend/saf/SafExtensions.kt#L56

The first API call is annotated by `@RequiresPermission`, while the last two are not. Do they also need the annotations?

Besides, I have two more suggestions about improving the code:

1. use runtime permission check before using the API:
```java
if(context.checkSelfPermission(ACCESS_MEDIA_LOCATION)==GRANTED)
    // call the API
```
2. use runtime version check before using the API:
```java
if(SDK_INT >= 29)
    // call the API
```

@FunkyMuse Could you help me review this? Very thanks!

**Comment by FunkyMuse** [comment]
Nice catch, you're right, every time `MediaStore.setRequireOriginal(Uri)` is called the permission is required above sdk 29, you can't even make that call below 29.

Meaning that those missing annotations are

```kotlin
@RequiresApi(Build.VERSION_CODES.Q)
@RequiresPermission(ACCESS_MEDIA_LOCATION)
```

**Comment by FunkyMuse** [comment]
Feel free to make a PR

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/KAHelpers/commit/d9255e1083e5855a62bc0299331b3e719cbecbc0
