### ISSUE TITLE
Useless functions removeFirstChar and removeLastChar.

### ISSUE THREAD

**Issue by MairwunNx** [FunkyMuse/KAHelpers#171]
https://github.com/FunkyMuse/KAHelpers/blob/e40d6c5b09ef8439b8e7fc1d2b92f1735bf4e111/string/src/main/java/com/crazylegend/string/StringExtensions.kt#L55-L69

This function no need, kotlin have functions `drop` and `dropLast`.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/drop.html

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/KAHelpers/commit/7165f90a43616391afa35921f5a13fd35870cdfb
