### ISSUE TITLE
isPhone extension implementation is strongly incorrect.

### ISSUE THREAD

**Issue by MairwunNx** [FunkyMuse/KAHelpers#172]
https://github.com/FunkyMuse/KAHelpers/blob/e40d6c5b09ef8439b8e7fc1d2b92f1735bf4e111/string/src/main/java/com/crazylegend/string/StringExtensions.kt#L91-L95

this regex fully incorrect and no matches much of possible numbers. `^1([34578])\\d{9}\$`

![image](https://user-images.githubusercontent.com/39625750/142617029-3f97e35a-e369-40d6-a92b-01d38ad84ab6.png)

Phone always must not checked or validated by regex because not one regex for all phone number cases. Phone always validating by code, or by regex but for only one culture.

**Comment by FunkyMuse** [comment]
Closed https://github.com/FunkyMuse/KAHelpers/commit/43e87010e18d5f9dc43c6ff72dc79cc8132404e8
