### ISSUE TITLE
Using regex for checking string is number, its overengineering

### ISSUE THREAD

**Issue by MairwunNx** [FunkyMuse/KAHelpers#174]
https://github.com/FunkyMuse/KAHelpers/blob/e40d6c5b09ef8439b8e7fc1d2b92f1735bf4e111/string/src/main/java/com/crazylegend/string/StringExtensions.kt#L110-L114

Using regex for this trivial task its overengineering, by the way, numbers like "3.14" will returns false :).
Never use regex for this, you can just write return `"3.14".toFloatOrNull() != null`

**Comment by FunkyMuse** [comment]
https://github.com/FunkyMuse/KAHelpers/commit/144ed8ed08576cab0a0e8d9b1cf474f899af8b14
