### ISSUE TITLE
Unable to resolve after name change

### ISSUE THREAD

**Issue by CarlosEsco** [FunkyMuse/KAHelpers#23]
gradle is unable to resolve 

com.github.FunkyMuse:KAHelpers:viewbinding

the others i am using coroutine, kotlinextensions, recyclerview are fine

**Comment by FunkyMuse** [comment]
> gradle is unable to resolve
> 
> com.github.FunkyMuse:KAHelpers:viewbinding
> 
> the others i am using coroutine, kotlinextensions, recyclerview are fine

    `implementation "com.github.FunkyMuse.KAHelpers:viewbinding:$utilsVersion"`

There's a typo : after FunkyMuse

**Comment by CarlosEsco** [comment]
:+1:
