### ISSUE TITLE
remove all @Nullable annotation 

### ISSUE THREAD

**Issue by milan-tejani-i2i** [FunkyMuse/KAHelpers#382]
kotlin provide nullable keyword "?" to make variable nullable so no need to use "Nullable" annotation @FunkyMuse 

i am also ready to contribute on this project for this issue.

**Comment by FunkyMuse** [comment]
Feel free to open a PR

**Comment by TheMilanTej** [comment]
@FunkyMuse working on it

**Comment by FunkyMuse** [comment]
let me know when it's ready for review

**Comment by TheMilanTej** [comment]
@FunkyMuse please check the pull request

**Comment by FunkyMuse** [comment]
Done, thanks
