### ISSUE TITLE
viewBinding issue

### ISSUE THREAD

**Issue by hamed2396** [FunkyMuse/KAHelpers#401]
hi. im trying to use view binding extension function but it wont work .i initilize it in my fragment like this :

**  private val binding by viewBinding(FragmentHomeBinding::bind) **

**override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return binding.root
    }**

but when running application it gives an error ->

**  java.lang.IllegalStateException: Fragment HomeFragment{42e81c4} (b0b54e5a-4677-4e6c-90ac-40a613953041 id=0x7f09021c) did not return a View from onCreateView() or this was called before onCreateView(). **
![image](https://github.com/FunkyMuse/KAHelpers/assets/86206868/cf7f2a71-8785-4e46-bd3e-321b74cd348b)

**Comment by Ammar-Ishfaq** [comment]
Hi, Just try with `by lazy` keyword because it'll initialize that on runtime when required.

**Comment by hamed2396** [comment]
> Hi, Just try with `by lazy` keyword because it'll initialize that on runtime when required.

can you provide me the code to initialize it? Im doing it like this but it's still giving me the same error
** private val binding by lazy {viewBinding (FragmentMyBinding::bind)}.value **

In on CreateView i return binding.root

**Comment by FunkyMuse** [comment]
you don't need 

```
override fun onCreateView(
inflater: LayoutInflater,
container: ViewGroup?,
savedInstanceState: Bundle?
): View {
return binding.root
}
```

at all

**Comment by FunkyMuse** [comment]
```
 private val binding by viewBinding(FragmentDetailsBinding::bind)
   
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        //do your things here
    }

```

**Comment by hamed2396** [comment]
> ```
>  private val binding by viewBinding(FragmentHomeBinding::bind)
>    
>     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
>         super.onViewCreated(view, savedInstanceState)
>         //do your things here
>     }
> ```

Thanks but i still didn't work .

**Comment by FunkyMuse** [comment]
> > ```
> >  private val binding by viewBinding(FragmentHomeBinding::bind)
> >    
> >     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
> >         super.onViewCreated(view, savedInstanceState)
> >         //do your things here
> >     }
> > ```
> 
> Thanks but it still didn't work .

remove this 
```
override fun onCreateView(
inflater: LayoutInflater,
container: ViewGroup?,
savedInstanceState: Bundle?
): View {
return binding.root
}
```

**Comment by hamed2396** [comment]
> > > ```
> > >  private val binding by viewBinding(FragmentHomeBinding::bind)
> > >    
> > >     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
> > >         super.onViewCreated(view, savedInstanceState)
> > >         //do your things here
> > >     }
> > > ```
> > 
> > 
> > Thanks but it still didn't work .
> 
> remove this
> 
> ```
> override fun onCreateView(
> inflater: LayoutInflater,
> container: ViewGroup?,
> savedInstanceState: Bundle?
> ): View {
> return binding.root
> }
> ```

I did what you told me to. but its not showing my layout . look 

![image](https://github.com/FunkyMuse/KAHelpers/assets/86206868/e88f990a-e9ee-4227-aaa5-e2a7d430a600)

**Comment by FunkyMuse** [comment]
Pass the R.layout inside the fragment consturctor

**Comment by hamed2396** [comment]
> Pass the R.layout inside the fragment consturctor

thanks it finally worked its a very easy way to initialize binding now. but i have a question . does this serve  the same purpose as doing it the old way ? i mean ->

  private var _binding: FragmentHomeBinding? = null
    private val binding get() = _binding!!

 override fun onDestroy() {

        super.onDestroy()
        _binding = null

    }

**Comment by FunkyMuse** [comment]
> > Pass the R.layout inside the fragment consturctor
> 
> thanks it finally worked its a very easy way to initialize binding now. but i have a question . does this serve the same purpose as doing it the old way ? i mean ->
> 
> private var _binding: FragmentHomeBinding? = null private val binding get() = _binding!!
> 
> override fun onDestroy() {
> 
> ```
>     super.onDestroy()
>     _binding = null
> 
> }
> ```

Yes it's essentially doing that so that you don't have to do it.
