### ISSUE TITLE
Add examples, docs to the README

### ISSUE THREAD

**Issue by kaushalyap** [FunkyMuse/KAHelpers#7]
There is no docs and no examples in the README, Please consider adding them

**Comment by CraZyLegenD** [comment]
Many of the extensions are pretty straight forward and do not need examples to do so, I believe anyone with common knowledge can get a grasp of them.

However this is an open source project and there's too many of them, as i'm working on another things...  
I would be needing help/contributions in adding the examples/wikis and/or READMEs, feel free to make a pull request regarding this.

**Comment by timusus** [comment]
I'd recommend you re-open this issue if you'd like help with it.

**Comment by FunkyMuse** [comment]
if someone can add dokka, i'd appreciate it, currently busy with other stuff

**Comment by rogergcc** [comment]
need a helper(extension)  fo **make readme doc** and examples.

**Comment by carstenhag** [comment]
Agree, would be nice to have this. I have seen this repo a few times but had no clue whether it is actually helpful, as there are no examples

**Comment by FunkyMuse** [comment]
> Agree, would be nice to have this. I have seen this repo a few times but had no clue whether it is actually helpful, as there are no examples

feel free to open a PR, it'll help a lot
dokka would be nice and easy integration

**Comment by 5peak2me** [comment]
It seems that Dokka does not support configuration cache, and in order to integrate Dokka, it needs to be disabled. For specific information, please refer to this link: https://github.com/Kotlin/dokka/issues/2612.
